### PR TITLE
[Merged by Bors] - Add map capabilities

### LINKED ISSUE #151: Add capability to use array_map
https://github.com/infinyon/fluvio-client-wasm/blob/8d9547ce0dc52a3f70aebeccd862d79997e290d6/src/consumer.rs#L20

https://github.com/infinyon/fluvio-client-wasm/blob/8d9547ce0dc52a3f70aebeccd862d79997e290d6/src/consumer.rs#L67

https://github.com/infinyon/fluvio-client-wasm/blob/8d9547ce0dc52a3f70aebeccd862d79997e290d6/src/consumer.rs#L88

### PR DESCRIPTION
**Pull request by joshchngs**
This fixes #151.

Tested under Firefox using local cluster (`flvd cluster start --local --develop`).

### CODE REVIEW

**Comment by joshchngs** [comment]
Updated with fmt fix.

Failing test is `simple`, which isn't touched by this PR - breakage on main?
It's temperamental locally.

**Review by morenol — CHANGES_REQUESTED** [review]
Thanks, nice work!

LGTM.

Could you rebase/merge this with `main` branch?

**Review by morenol — APPROVED** [review]
thanks!

**Review by morenol — CHANGES_REQUESTED** [review]
Sorry, one last change. 

Could you move these tests to `tests/smartmodule.rs`

**Comment by joshchngs** [comment]
Done

**Review by morenol — APPROVED** [review]

**Comment by morenol** [comment]
bors ping

**Comment by morenol** [comment]
bors ping

**Pull request closed without merging**
