### PR TITLE
Setup bors

### LINKED ISSUE #224: Use bors for PRs handling

### PR DESCRIPTION
**Pull request by morenol**
Closes #224

### CODE REVIEW

**Comment by morenol** [comment]
bors ping

**Review by simlay — COMMENTED** [review]
I think @pinkforest commented that our boss setup on Fluvio-connectors closes PR's rather than merging them.

**Comment by morenol** [comment]
> I think @pinkforest commented that our boss setup on Fluvio-connectors closes PR's rather than merging them.

Yes, I think that the plan is to solve that with:

> Future Changes
        Fail Staging run only if PR is not squashed merged. This means CI won't fail in the PR action
         Have a tool to squash merge. This only need to run prior to bors.

https://github.com/infinyon/fluvio-connectors/pull/136#issue-1120101634

**Pull request merged**
